package main

const (
	FAIL = "Fail"
	SUCCESS = "Success"
	REVERSAL = "Reversal"
	BEAST = "Beast"
)

const (
	GOOD = "Good"
	BAD = "Bad"
	NEUTRAL = "Neutral"
)

type CharacterDescription struct {
	Loyalty string `json:"loyalty,omitempty"`
	CanSee string `json:"canSee,omitempty"`
	CanVote []string `json:"canVote,omitempty"`
	CanVoteOnFlush []string `json:"canVoteOnFlush,omitempty"`
	MurderedBy string `json:"murderedBy,omitempty"`
	Murder string `json:"murder,omitempty"`
	SpecialRole string `json:"specialRole,omitempty"`
}

var CharactersDescriptionMap = map[string]CharacterDescription {
	"Merlin": {GOOD, "all evil and Gawain",
		[]string{SUCCESS},
		[]string{SUCCESS},
		"assassin",
		"",
		""},
	"Percival": {GOOD, "Merlin and Morgana but does not know who is who",
		[]string{SUCCESS},
		[]string{SUCCESS},
		"",
		"TBD",
		""},
	"Good-Angel": {GOOD, "", []string{SUCCESS, REVERSAL},
		[]string{SUCCESS}, "", "", ""},
	"Titanya": {GOOD, "",
		[]string{"In its first vote – Fail. After that - Success"},
		[]string{"According to the original voting rule."}, "", "", ""},
	"Nimue": {GOOD, "Merlin and Galahad",
		[]string{"In quest with Merlin, without Galahad – Fail. Otherwise - Success"},
		[]string{"According to the original voting rule."}, "", "", ""},
	"Galahad": {GOOD, "", []string{SUCCESS}, []string{SUCCESS}, "",
		"", ""},
	"Sir-Kay": {GOOD, "", []string{SUCCESS}, []string{SUCCESS}, "",
		"", "merlin see him with evil"},
	"Seer": {GOOD, "Pick player on his left/right and see its character.", []string{SUCCESS},
		[]string{SUCCESS}, "",
		"", ""},
	"King-Arthur": {GOOD, "", []string{"fake Fail, calculated as Success"},
		[]string{"fake Fail, calculated as Success"}, "",
		"all evil", ""},
	"Puck": {NEUTRAL, "", []string{SUCCESS, FAIL},
		[]string{SUCCESS}, "",
		"", "only wins if game reach the last quest and last quest is a win for good."},
	"Viviana": {GOOD, "after quest is accepted – can see the leader of the quest loyalty.",
		[]string{SUCCESS},
		[]string{SUCCESS}, "assassin",
		"", ""},
	"Tristan": {GOOD, "Iseult",
		[]string{SUCCESS},
		[]string{SUCCESS}, "assassin",
		"", ""},
	"Iseult": {GOOD, "Tristan",
		[]string{SUCCESS},
		[]string{SUCCESS}, "assassin",
		"", ""},
	"Prince-Claudin": {GOOD, "King-Claudin",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "losses if king Claudin merderd with evils"},
	"Nirlem": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "assassain",
		"", "Seen by all Goods."},
	"Sir-Robin": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "Loose game if chosen for more than 2 quests"},
	"Balain": {GOOD, "Balin",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "Switching loyalty with Balin when they go out to the same mission"},
	"Pellinore": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"The Beast",
		"Wins in the following cases: 1. Participate in quest together with the beast, beast vote “Beast” in this quest. 2. There is no quest with “Beast” card. 3. Murdered the Beast."},
	"Lot": {BAD, "All Bads.",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "Seen by Merlin, invisible to other Bads."},
	"Cordana": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"Mordred", ""},
	"The-Coward": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "if good wins he only loss if assassin kill him"},
	"Merlin-Apprentice": {GOOD, "Percival and assassin but does not know who is who ",
		[]string{SUCCESS},
		[]string{SUCCESS}, "assassin",
		"", ""},
	"Guinevere": {GOOD, "Two Lancelots, but does not know who is who",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", ""},
	"Bors": {GOOD, "one player that he want",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "get the grail"},
	"Sir-Gawain": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "winnig only if he got murdered insted of merlin or mordred"},
	"Uther-Pendragon": {GOOD, "",
		[]string{""},
		[]string{""}, "",
		"", "put empty card"},
	"Raven": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "lady of the lack see him as bad"},
	"Gornemant": {GOOD, "2 pairs",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "can see 2 players from same team and 2 players from opposite team dosnt know which pair is what"},
	"Blanchefleur": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "see 2 claims:1.player A see player B 2. player C see player D. only one of them is true"},
	"Tom-Thumb": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "if bad have one more mission to win he can see 2 good guys that he choose"},
	"Jarvan": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "can reveal himself if:1. excalibur giving to him and wont change is vote 2.from the secend round if he isnt in the mission he can reverse a vote if its not fail he cant be picked anymore for missions 3.in the last mission if he didnt reveal himself antil then he can change any vote that he want. if good wins he can protect one player from assassin"},
	"Agravain": {BAD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", ""},
	"Ector": {GOOD, "",
		[]string{""},
		[]string{}, "",
		"", "cant go out for a mission"},
	"Elaine": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "can use Avalon Power card to cancel a mission"},
	"Lancelot-Good": {GOOD, "",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "Switching loyalty with Lancelot-Bad In probability of 2/7"},
	"Morgana": {BAD, "All evil and Gawain",
		[]string{SUCCESS,FAIL},
		[]string{FAIL}, "king Arthur",
		"", ""},
	"Assassin": {BAD, "All evil",
		[]string{SUCCESS,FAIL},
		[]string{FAIL}, "king Arthur",
		"", ""},
	"Mordred": {BAD, "All evil",
		[]string{SUCCESS,FAIL},
		[]string{FAIL}, "cordana or king Arthur",
		"", "Invisible to Merlin"},
	"Oberon": {BAD, "",
		[]string{SUCCESS,FAIL},
		[]string{FAIL}, "king Arthur",
		"", "Invisible to evil."},
	"Bad-Angel": {BAD, "All evil",
		[]string{SUCCESS,FAIL,REVERSAL},
		[]string{FAIL}, "king Arthur",
		"", ""},
	"King-Claudin": {BAD, "All evil and Prince-Claudin",
		[]string{SUCCESS,FAIL},
		[]string{FAIL}, "king Arthur",
		"", ""},
	"Ginerva": {NEUTRAL, "",
		[]string{SUCCESS,FAIL},
		[]string{FAIL}, "",
		"", "only wins if game reach the last quest and last quest is a win for evil."},
	"Polygraph": {BAD, "All evil",
		[]string{FAIL},
		[]string{FAIL}, "king Arthur",
		"", "all evil know her as Polygraph"},
	"The-Questing-Beast": {BAD, "All evil",
		[]string{"Beast. Can vote Success only once"},
		[]string{FAIL}, "king Arthur or Palinode ",
		"", "Wins in one of the following: 1. didn’t voted “Beast” in any quest that Palinode was part of it. 2. Wasn’t murdered by the Pellinore."},
	"Accolon": {BAD, "",
		[]string{FAIL,SUCCESS},
		[]string{FAIL}, "king Arthur",
		"", "Invisible to Merlin and evil."},
	"Gawain": {NEUTRAL, "All evil, Merlin and Percival but doesn’t know who is who",
		[]string{FAIL,SUCCESS},
		[]string{SUCCESS, FAIL}, "",
		"", "Seen by Merlin and Morgana. He also have a double vote for the last quest. If he is chosen to this quest, he is the only winner of the game, regardless to the quest result."},
	"Lancelot-Bad": {BAD, "",
		[]string{FAIL},
		[]string{FAIL}, "king Arthur",
		"", "Switching loyalty with Lancelot-good In probability of 2/7"},
	"Queen-Mab": {BAD, "All evil",
		[]string{FAIL, SUCCESS},
		[]string{FAIL}, "king Arthur",
		"", "Can lie to the lady of the lake"},
	"Nerzhul": {BAD, "All evil and Oberon",
		[]string{FAIL, SUCCESS},
		[]string{FAIL}, "king Arthur",
		"", ""},
	"Stray": {"Unknown", "Unknown",
		[]string{FAIL, SUCCESS},
		[]string{}, "Unknown",
		"", "can be good rule or mordred no one know"},
	"Balin": {BAD, "Balain",
		[]string{FAIL},
		[]string{FAIL}, "king Arthur",
		"", "Switching loyalty with Balain when they go out to the same mission"},
	"Mora": {BAD, "All evil",
		[]string{FAIL, SUCCESS},
		[]string{FAIL, SUCCESS}, "king Arthur",
		"", "dosnt have to put fail when graal activeted"},
	"Meliagant": {BAD, "All evil",
		[]string{FAIL, SUCCESS},
		[]string{FAIL}, "king Arthur",
		"", "Can see the evil that the other evil cant see"},
	"Dagonet": {NEUTRAL, "Oberon",
		[]string{SUCCESS},
		[]string{SUCCESS}, "",
		"", "win only if assassin kill Merlin or Oberon"},
	"Melwas": {BAD, "all Evil",
		[]string{SUCCESS},
		[]string{SUCCESS}, "king Arthur",
		"", "can look in the firs plot card and cancel it"},
	"Maeve": {BAD, "All evil",
		[]string{FAIL, SUCCESS},
		[]string{FAIL}, "king Arthur",
		"", "Immune to Excalibur"},

}