version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: avalonDB
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend

  server:
    image: avalon:tiny
    tty: true
    stdin_open: true 
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '12345:12345'
    depends_on:
      - 'mongo'
    environment:
      - MONGO_ADDRESS=mongo
    networks:
      - backend
      - frontend
  
  client:
    image: avalon-nginx:1.0.0
    tty: true
    stdin_open: true 
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    networks:
      - frontend

networks:
  frontend:
    external: false
  backend:
    external: false

