version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: avalonDB
    ports:
      - '27017-27019:27017-27019'


  # avalon-server:
  #   image: avalon-server
  #   tty: true
  #   stdin_open: true 
  #   build:
  #     context: .
  #     dockerfile: server.Dockerfile
  #   ports:
  #     - '12345:12345'
  #   depends_on:
  #     - 'mongo'
