FROM node:16.16-alpine3.15 as BUILD
WORKDIR /app

COPY ./client/package.json ./client/package-lock.json ./
RUN npm install
COPY ./client .
RUN npm run build --prod -- --output-path=./dist/out

FROM nginx:1.23.1-alpine
COPY --from=BUILD /app/dist/out/ /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 12345
