version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: avalonDB
    ports:
      - '27017-27019:27017-27019'


  server:
    image: avalon:tiny
    tty: true
    stdin_open: true 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '12345:12345'
    depends_on:
      - 'mongo'
    environment:
      - MONGO_ADDRESS=mongo

