package main

const (
	FAIL = "Fail"
	SUCCESS = "Success"
	REVERSAL = "Reversal"
	BEAST = "Beast"
	EMPTY = "Empty"
	AVALON_POWER = "Avalon Power"
)

const (
	GOOD = "Good"
	BAD = "Bad"
	NEUTRAL = "Neutral"
)

type CharacterDescription struct {
	Loyalty string `json:"loyalty,omitempty"`
	CanSeeAsColor []string `json:"canSeeAsColor,omitempty"`
	CanSeeSpecifically []string `json:"canSeeSpecifically,omitempty"`
	SeenAsColorBy []string `json:"seenAsColorBy,omitempty"`
	SeenSpecificallyBy []string `json:"seenSpecificallyBy,omitempty"`

	CanVote []string `json:"canVote,omitempty"`
	CanVoteOnFlush []string `json:"canVoteOnFlush,omitempty"`
	MurderedBy []string `json:"murderedBy,omitempty"`
	Murder []string `json:"murder,omitempty"`
	SpecialRole string `json:"specialRole,omitempty"`
}

var CharactersDescriptionMap = map[string]CharacterDescription{
	Merlin: {GOOD,
		[]string{Morgana, Assassin, BadAngel, KingClaudin, Polygraph,
			LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, SirKay, Melwas, Claudas,
			MinionOfMordred, Meliagant},
		[]string{Oberon, Nirlem, Lot, Stray, Gawain, Ector},
		[]string{Gawain, Percival},
		[]string{Nimue},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{Assassin},
		[]string{},
		"He has a lot of information but he has to be careful not to be killed at the end of the game",
	},
	Percival: {GOOD,
		[]string{Merlin, Morgana, Viviana},
		[]string{Nirlem, Ector},
		[]string{MerlinApprentice, Gawain},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{""},
		[]string{Morgana, Assassin, BadAngel, KingClaudin, Polygraph, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Oberon, Lot, Mordred, Accolon, Agravain, Meliagant},
		"He has a lot of information but he has to be careful not to be killed at the end of the game",
	},
	Titanya: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{"Fail in first quest and Success any other time"},
		[]string{"Fail in first quest and Success any other time"},
		[]string{""},
		[]string{},
		"need to put fail in the first quest she play unless it’s the last one for the bad to win",
	},
	Nimue: {GOOD,
		[]string{},
		[]string{Merlin, Galahad, Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{"success unless she go to a quest with Merlin and without Galahad"},
		[]string{"success unless she go to a quest with Merlin and without Galahad"},
		[]string{""},
		[]string{},
		"she will put fail only if she goes to a quest with Merlin and without Galahad",
	},
	Galahad: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{""},
		[]string{},
		"saving Nimue when she goes to a quest with Merlin",
	},
	SirKay: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{Merlin},
		[]string{Claudas},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{""},
		[]string{},
		"a good player that merlin sees as bad one",
	},
	Seer: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{""},
		[]string{},
		"can she one player role that seats next to him",
	},
	KingArthur: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{"fake Fail"},
		[]string{"fake Fail"},
		[]string{""},
		[]string{Morgana, Assassin, BadAngel, KingClaudin, Polygraph, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Oberon, Lot, Mordred, Accolon, Agravain, Meliagant},
		"can put only fake fail we all will see the fail but the game know its not a real fail, if bad guys won he can try to kill them all if he correct good guys win",
	},
	Puck: {NEUTRAL,
		[]string{},
		[]string{Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS, FAIL},
		[]string{SUCCESS},
		[]string{""},
		[]string{},
		"to win he need to get to the last quest on the bored and that the last quest will be a success",
	},
	Viviana: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{Percival, Gawain},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{Assassin},
		[]string{},
		"if the quest was approved she can see the loyalty or the role of the leader but need to be carful with the information assassin can murder her in the end",
	},
	Tristan: {GOOD,
		[]string{},
		[]string{Nirlem, Ector, Iseult},
		[]string{},
		[]string{Iseult},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{Assassin},
		[]string{},
		"can see his lover Iseult but Assassin can kill them both in the end",
	},
	Iseult: {GOOD,
		[]string{},
		[]string{Nirlem, Ector, Tristan},
		[]string{},
		[]string{Tristan},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{Assassin},
		[]string{},
		"can see his lover Tristan but Assassin can kill them both in the end",
	},
	PrinceClaudin: {GOOD,
		[]string{},
		[]string{Nirlem, Ector, KingClaudin},
		[]string{},
		[]string{KingClaudin},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can see is bad dad and need to make everyone believe he is good",
	},
	Nirlem: {GOOD,
		[]string{},
		[]string{Ector},
		[]string{Gawain},
		[]string{Merlin, Percival, GoodAngel, Titanya, Nimue, Galahad, SirKay, Seer, KingArthur, Viviana, Tristan, Iseult, PrinceClaudin, SirRobin, Cordana, TheCoward, LoyalServentOfArthur, MerlinApprentice, Guinevere, Raven, SirGawain, Ector, Elaine, Blanchefleur, TomThumb, Gornemant, Bors, UtherPendragon, Jarvan},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{Assassin},
		[]string{},
		"he doesn’t have any info but all good roles sees him and need to save him from Assassin",
	},
	SirRobin: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"will lose if he go to more then 2 quest in small board or more then 3 quest in big board",
	},
	Pellinore: {NEUTRAL,
		[]string{},
		[]string{Ector},
		[]string{},
		[]string{TheQuestingBeast},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{TheQuestingBeast},
		"can win only if 1. The beast didn’t put beast card or 2. If he and the beast was on the same quest and the beast used beast card in it or 3. If he kill the beast in the end of the game",
	},
	Lot: {BAD,
		[]string{Morgana, Assassin, BadAngel, KingClaudin, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Mordred, Meliagant},
		[]string{Ector, Polygraph, Stray},
		[]string{Gawain},
		[]string{Merlin, Viviana, Meliagant},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{KingArthur, Percival},
		[]string{},
		"bad that can only put success",
	},
	Cordana: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{Mordred},
		"if the bad guys win he can try to kill Mordred if he was correct the Assassin can try to kill too",
	},
	TheCoward: {GOOD,
		[]string{},
		[]string{Ector, Nirlem},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"will loss if Assassin kill him in the end",
	},
	LoyalServentOfArthur: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"loyal servant",
	},
	MerlinApprentice: {GOOD,
		[]string{Percival, Assassin},
		[]string{Percival, Assassin},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{Assassin},
		[]string{},
		"see Percival and Assassin but doesn’t know who is who can be killed in the end of the game",
	},
	Guinevere: {GOOD,
		[]string{LancelotGood, LancelotBad},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can see both Lancelot but cant tell who is the bad one and who is the good one",
	},
	LancelotGood: {GOOD,
		[]string{},
		[]string{Ector},
		[]string{Guinevere},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"have a chance of 2/7 to  switch role with Lancelot-Bad",
	},
	Raven: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"if she get Lady of the lake she need to return bad",
	},
	GoodAngel: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS, REVERSAL},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can put the reversal card and reverse the outcome of the quest",
	},
	Balain: {GOOD,
		[]string{},
		[]string{Ector, Balin},
		[]string{},
		[]string{Balin},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"if he and Balin are in the same quest they switch role",
	},
	SirGawain: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"if anyone kill him in the end of the game he is the only winner of the game",
	},
	Stray: {"Unknown",
		[]string{"Unknown"},
		[]string{"Unknown", Ector},
		[]string{"Unknown"},
		[]string{Merlin, Viviana, Morgana, Assassin, BadAngel, KingClaudin, Polygraph, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Lot, Mordred, Agravain, Meliagant},
		[]string{"Unknown"},
		[]string{"Unknown"},
		[]string{"Unknown"},
		[]string{"Unknown"},
		"can be 50% Mordred or 50% random good role",
	},
	Ector: {GOOD,
		[]string{},
		[]string{Nirlem},
		[]string{},
		[]string{Merlin, Percival, GoodAngel, Titanya, Nimue, Galahad, SirKay, Seer, KingArthur, Puck, Viviana, Tristan, Iseult, PrinceClaudin, Nirlem, SirRobin, Pellinore, Lot, Cordana, TheCoward, LoyalServentOfArthur, MerlinApprentice, Guinevere, LancelotGood, Raven, Balain, SirGawain, Stray, Elaine, Blanchefleur, TomThumb, Gornemant, Dagonet, Agravain, Bors, UtherPendragon, Morgana, Assassin, Mordred, Oberon, BadAngel, KingClaudin, Ginerva, Polygraph, TheQuestingBeast, Accolon, Gawain, LancelotBad, QueenMab, Balin, Maeve, Meliagant, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Jarvan},
		[]string{},
		[]string{},
		[]string{},
		[]string{},
		"everyone can see him and he cant go to any quests",
	},
	Elaine: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS, AVALON_POWER},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can put Avalon power and cancel the quest once in a game",
	},
	Blanchefleur: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can she 2 pair of players each one that see someone (he got glass ) and one that seen by him ( the same color one ) only one of them is true",
	},
	TomThumb: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"if bad guys are one more quest from wining he can choose 2 good role to see ",
	},
	Gornemant: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can see 2 pairs of colors one of them is 2 roles with the same loyalty and the other is 2 roles that in different loyalties",
	},
	Dagonet: {NEUTRAL,
		[]string{},
		[]string{Oberon, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can only win if Assassin kill Oberon or Merlin can help Assassin to choose",
	},
	Meliagant: {BAD,
		[]string{},
		[]string{Ector, Lot, Morgana, Assassin, Mordred, Oberon, BadAngel, KingClaudin, Polygraph, Accolon, LancelotBad, QueenMab, Balin, Maeve, Agravain, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Stray},
		[]string{Merlin, Viviana, Lot, Morgana, Assassin, Mordred, BadAngel, KingClaudin, Polygraph, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Gawain},
		[]string{},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"replace good guy role and all the quest in the game need 1 less player can see all the bad guys specific include the one that the other bad guys doesn’t see",
	},
	Bors: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"if the Grail is used on him he can tell who he is and look on 1 of the players that he like",
	},
	UtherPendragon: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{EMPTY},
		[]string{EMPTY},
		[]string{},
		[]string{},
		"can only put empty card ",
	},
	Jarvan: {GOOD,
		[]string{},
		[]string{Nirlem, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{},
		[]string{},
		"can reveal himself if 1. Someone used Excaliber on him and then his vote stay success or 2. If he isn’t in the quest and he want to take excaliber and use it on someone and then if he correct its ok but if he use it on success he cant join to any more quests for the res of the game or 3. If he didn’t reveal himself until the last quest he can reveal himself and use the excaliber on as many player he want. If he revealed himself he can protect one player from been murdered",
	},
	Morgana: {BAD,
		[]string{Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Gawain, Polygraph, Ector, Stray},
		[]string{Assassin, Mordred, BadAngel, KingClaudin, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Lot, Gawain, Percival, Merlin, Viviana},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"can try to confuse Percival",
	},
	Assassin: {BAD,
		[]string{Morgana, Mordred, BadAngel, KingClaudin, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Ector, Polygraph, Stray},
		[]string{Morgana, Mordred, BadAngel, KingClaudin, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Lot, Gawain, Merlin, Viviana, MerlinApprentice},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{Merlin, Viviana, MerlinApprentice, Tristan, Iseult, Nirlem},
		"can kill in the end of the game and win the game for bad guys",
	},
	Mordred: {BAD,
		[]string{Assassin, Morgana, BadAngel, KingClaudin, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Polygraph, Ector, Stray},
		[]string{Assassin, Morgana, BadAngel, KingClaudin, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Lot, Gawain},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur, Cordana},
		[]string{},
		"invisible to the good ",
	},
	Oberon: {BAD,
		[]string{},
		[]string{Ector},
		[]string{Gawain},
		[]string{Meliagant, Nerzhul, Claudas, Dagonet, Merlin, Viviana},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"doesn’t know the bads and they don’t know him",
	},
	BadAngel: {BAD,
		[]string{Morgana, Mordred, Assassin, KingClaudin, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Polygraph, Ector, Stray},
		[]string{Gawain, Merlin, Viviana, Morgana, Mordred, Assassin, KingClaudin, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Lot},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL, REVERSAL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"can put the reversal card and reverse the outcome of the quest",
	},
	KingClaudin: {BAD,
		[]string{Morgana, Mordred, Assassin, BadAngel, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Ector, Polygraph, PrinceClaudin, Stray},
		[]string{Gawain, Merlin, Viviana, Morgana, Mordred, Assassin, BadAngel, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Lot},
		[]string{PrinceClaudin, Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"the prince must keep him alive",
	},
	Ginerva: {NEUTRAL,
		[]string{},
		[]string{Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{},
		[]string{},
		"to win she need to get to the last quest on the bored and that the last quest will be a fail",
	},
	Polygraph: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, QueenMab, Balin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Ector, Stray},
		[]string{Gawain, Merlin, Viviana},
		[]string{Lot, Morgana, Assassin, Mordred, BadAngel, KingClaudin, QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Meliagant},
		[]string{FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"can only do fail",
	},
	TheQuestingBeast: {NEUTRAL,
		[]string{},
		[]string{Pellinore, Ector},
		[]string{},
		[]string{},
		[]string{SUCCESS, BEAST},
		[]string{FAIL},
		[]string{Pellinore},
		[]string{},
		"can win if 1. She play best card and didn’t went with Pellinore in the same quest or 2. Pellinore didn’t killed her. Can only use success 1 time in the game",
	},
	Accolon: {BAD,
		[]string{},
		[]string{Ector},
		[]string{Gawain},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"invisible to good and bad",
	},
	Gawain: {NEUTRAL,
		[]string{Merlin, Morgana, Percival, Assassin, Mordred, Oberon, BadAngel, KingClaudin, Polygraph,
			LancelotBad, QueenMab, Balin, Viviana, Nirlem, Maeve, Meliagant, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Ector},
		[]string{},
		[]string{Merlin, Viviana, Morgana},
		[]string{SUCCESS, FAIL},
		[]string{FAIL, SUCCESS},
		[]string{},
		[]string{},
		"need to go to the last quest and be on it and if he dose that he is the only winner of the game, if he is part of this quest he gor 2 vote to approve",
	},
	LancelotBad: {BAD,
		[]string{},
		[]string{Ector},
		[]string{Guinevere, Morgana, Merlin, Viviana, Assassin, Mordred, BadAngel, KingClaudin, Polygraph,
			QueenMab, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, Gawain, Lot},
		[]string{Meliagant},
		[]string{FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"have a chance of 2/7 to  switch role with Lancelot-Good",
	},
	QueenMab: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, Balin, Maeve, Nerzhul,
			Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Polygraph, Ector, Stray},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin, Maeve,
			Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"can lie to Lady of the lake",
	},
	Balin: {BAD,
		[]string{},
		[]string{Balain, Ector},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin, Maeve, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred, QueenMab},
		[]string{Meliagant, Balain},
		[]string{FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"if he and Balain are in the same quest they switch role",
	},
	Maeve: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, Balin, QueenMab,
			Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Ector, Polygraph, Stray},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin,
			QueenMab, Nerzhul, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"immune to Excalibur",
	},
	Agravain: {BAD,
		[]string{},
		[]string{Ector},
		[]string{Gawain},
		[]string{Meliagant},
		[]string{SUCCESS},
		[]string{SUCCESS},
		[]string{Percival, KingArthur},
		[]string{},
		"playing as good but win with the bads",
	},
	Nerzhul: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, Balin, QueenMab,
			Maeve, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Ector, Oberon, Polygraph, Stray},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin,
			QueenMab, Maeve, Mora, Melwas, Claudas, MinionOfMordred},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"can see oberon",
	},
	Mora: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, Balin, QueenMab,
			Nerzhul, Maeve, Melwas, Claudas, MinionOfMordred},
		[]string{Ector, Polygraph, Stray},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin,
			QueenMab, Nerzhul, Maeve, Melwas, Claudas, MinionOfMordred},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{SUCCESS, FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"can vote success in flash and graal quests",
	},
	Melwas: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, Balin, QueenMab,
			Nerzhul, Mora, Maeve, Claudas, MinionOfMordred},
		[]string{Ector, Polygraph, Stray},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin,
			QueenMab, Nerzhul, Mora, Maeve, Claudas, MinionOfMordred},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"can look in pilot card and cancel first card",
	},
	Claudas: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, Balin, QueenMab,
			Nerzhul, Mora, Melwas, Maeve, MinionOfMordred},
		[]string{Ector, Polygraph, Oberon, SirKay, Stray},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin,
			QueenMab, Nerzhul, Mora, Melwas, Maeve, MinionOfMordred},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"win with the bads if they won on quests and if Sir-Kay or Oberon get murdred in the end",
	},
	MinionOfMordred: {BAD,
		[]string{Morgana, Assassin, Mordred, BadAngel, KingClaudin, LancelotBad, Balin,
			QueenMab, Nerzhul, Mora, Melwas, Claudas, Maeve},
		[]string{Ector, Polygraph, Stray},
		[]string{Lot, Merlin, Morgana, Viviana, Gawain, Assassin, Mordred, BadAngel, KingClaudin,
			QueenMab, Nerzhul, Mora, Melwas, Claudas, Maeve},
		[]string{Meliagant},
		[]string{SUCCESS, FAIL},
		[]string{FAIL},
		[]string{Percival, KingArthur},
		[]string{},
		"Minion-Of-Mordred",
	},
}